name: Build everything on merge

on:
  push:
    branches:
      - "main"

jobs:
  test-library:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project sources
        uses: actions/checkout@v3
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Run fyeolib tests
        run: ./gradlew fyeolib:clean fyeolib:test

  test-flyway-plugin:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project sources
        uses: actions/checkout@v3
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Run flyway plugin tests
        run: ./gradlew flyway-plugin:clean flyway-plugin:test

  test-aws-secretmanager-driver:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project sources
        uses: actions/checkout@v3
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Run aws secretmanager plugin tests
        run: ./gradlew aws-secretmanager:clean aws-secretmanager:test

  test-examples:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project sources
        uses: actions/checkout@v3
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Run AWS Flyway example tests
        run: ./gradlew aws-flyway-example:clean aws-flyway-example:test

  publish-jars:
    if: "contains(github.event.head_commit.message, '[PUBLISH]')"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project sources
        uses: actions/checkout@v3
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Publish fyeolib
        run: ./gradlew fyeolib:publish