name: Build everything on merge

on:
  push:
    branches:
      - "main"

jobs:
  thing:
    runs-on: ubuntu-latest
    if: "contains(github.event.pull_request.title, '[PUBLISH]')"
    steps:
      - run: echo "HELLO"
  test-library:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project sources
        uses: actions/checkout@v3
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Run fyeolib tests
        run: ./gradlew fyeolib:clean fyeolib:test

  test-flyway-plugin:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project sources
        uses: actions/checkout@v3
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Run flyway plugin tests
        run: ./gradlew flyway-plugin:clean flyway-plugin:test

  test-aws-secretmanager-driver:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project sources
        uses: actions/checkout@v3
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Run aws secretmanager plugin tests
        run: ./gradlew aws-secretmanager:clean aws-secretmanager:test

  test-examples:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project sources
        uses: actions/checkout@v3
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Run AWS Flyway example tests
        run: ./gradlew aws-flyway-example:clean aws-flyway-example:test

  publish-fyeolib:
    runs-on: ubuntu-latest
    if: "contains(github.event.head_commit.message, '[PUBLISH]')"
    steps:
      - name: Import GPG Key
        uses: crazy-max/ghaction-import-gpg@v1
        env:
          GPG_PRIVATE_KEY: ${{ secrets.GPG_SIGNING_KEY }}
          PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
      - name: Checkout project sources
        uses: actions/checkout@v3
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Publish fyeolib
        env:
          ORG_GRADLE_PROJECT_nexusUsername: ${{ secrets.ORG_GRADLE_PROJECT_nexusUsername }}
          ORG_GRADLE_PROJECT_nexusPassword: ${{ secrets.ORG_GRADLE_PROJECT_nexusPassword }}
        run: ./gradlew fyeolib:build fyeolib:publish -x test

  publish-aws-secretmanager:
    if: "contains(github.event.head_commit.message, '[PUBLISH]')"
    runs-on: ubuntu-latest
    steps:
      - name: Import GPG Key
        uses: crazy-max/ghaction-import-gpg@v1
        env:
          GPG_PRIVATE_KEY: ${{ secrets.GPG_SIGNING_KEY }}
          PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
      - name: Checkout project sources
        uses: actions/checkout@v3
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Publish aws secretmanager driver
        env:
          ORG_GRADLE_PROJECT_nexusUsername: ${{ secrets.ORG_GRADLE_PROJECT_nexusUsername }}
          ORG_GRADLE_PROJECT_nexusPassword: ${{ secrets.ORG_GRADLE_PROJECT_nexusPassword }}
        run: ./gradlew aws-secretmanager:build aws-secretmanager:publish -x test

  publish-flyway-plugin:
    if: "contains(github.event.head_commit.message, '[PUBLISH]')"
    runs-on: ubuntu-latest
    steps:
      - name: Import GPG Key
        uses: crazy-max/ghaction-import-gpg@v1
        env:
          GPG_PRIVATE_KEY: ${{ secrets.GPG_SIGNING_KEY }}
          PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
      - name: Checkout project sources
        uses: actions/checkout@v3
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Publish flyway plugin
        env:
          ORG_GRADLE_PROJECT_nexusUsername: ${{ secrets.ORG_GRADLE_PROJECT_nexusUsername }}
          ORG_GRADLE_PROJECT_nexusPassword: ${{ secrets.ORG_GRADLE_PROJECT_nexusPassword }}
        run: ./gradlew flyway-plugin:build flyway-plugin:publish -x test