name: Run unit tests

on:
  push:
    branches:
      - "*"

jobs:
  test-library:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project sources
        uses: actions/checkout@v3
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Run fyeolib tests
        run: ./gradlew fyeolib:clean fyeolib:test
      - name: Run flyway plugin tests
        run: ./gradlew flyway-plugin:clean flyway-plugin:test
      - name: Run aws secretmanager plugin tests
        run: ./gradlew aws-secretmanager:clean aws-secretmanager:test

  test-examples:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project sources
        uses: actions/checkout@v3
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Run AWS Flyway example tests
        run: ./gradlew aws-flyway-example:clean aws-flyway-example:test